import React, { Component } from "react";
import ListGroup from "react-bootstrap/ListGroup";
import Card from "react-bootstrap/Card";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import "./newPlayerPage.css";

class NewPlayerPage extends Component {
  state = {
    draftYear: "/newPlayerImages/draft_year.png",
    position: "/newPlayerImages/position.png",
    numberOfYear: "/newPlayerImages/number_of_year.png",
    clusterNumber: "/newPlayerImages/cluster_number.png",
    cluster: "/newPlayerImages/cluster.png",
    clusterNumberDistribution:
      "/newPlayerImages/cluster_number_distribution.png",
    position_distrution_png: "/newPlayerImages/position_distribution.png",
    new_player_distribution_png: "/newPlayerImages/new_player_distribution.png",
    result: "/newPlayerImages/result.png",
  };

  render() {
    return (
      <Card>
        <Card.Body>
          <Card.Title>New Player Analysis Presentation</Card.Title>
          <Card.Text>
            This presentation used Orlando Johnson as an example
          </Card.Text>
          <Card style={{ marginLeft: "2%" }}>
            <Card.Body>
              <Card.Title>Distributions of the Players'drafted Year</Card.Title>
              <img className="img-format" src={this.state.draftYear} />
            </Card.Body>
            <Card style={{ marginLeft: "2%" }}>
              <Card.Body>
                <Card.Title>
                  Distributions of Players for each Positions from 2010 to 2020
                </Card.Title>
                <img className="img-format" src={this.state.position} />
              </Card.Body>
              <Card style={{ marginLeft: "2%" }}>
                <Card.Body>
                  <Card.Title>
                    Distributions of Players's drafted year from 2010 to 2020
                  </Card.Title>
                  <img className="img-format" src={this.state.numberOfYear} />
                </Card.Body>
                <Card style={{ marginLeft: "2%" }}>
                  <Card.Body>
                    <Card.Title>
                      Through plot, K=7 will be good to use clusters which
                      generated by K mean to classify our data
                    </Card.Title>
                    <img
                      className="img-format"
                      src={this.state.clusterNumber}
                    />
                  </Card.Body>
                  <Card style={{ marginLeft: "2%" }}>
                    <Card.Body>
                      <Card.Title>
                        This is how our data classified by K mean reflected in
                        two dimensions
                      </Card.Title>
                      <img className="img-format" src={this.state.cluster} />
                    </Card.Body>
                    <Card style={{ marginLeft: "2%" }}>
                      <Card.Body>
                        <Card.Title>
                          Distribution of Players for each cluster
                        </Card.Title>
                        <img
                          className="img-format"
                          src={this.state.clusterNumberDistribution}
                        />
                      </Card.Body>
                      <Card style={{ marginLeft: "2%" }}>
                        <Card.Body>
                          <Card.Title>
                            How our data classified by player_position and
                            top-100 players' name was labeled on it.
                          </Card.Title>
                          <Card.Text>
                            Trying to use Kmean cluster to classify, but
                            position make more sense.
                          </Card.Text>
                          <img
                            className="img-format_version2"
                            src={this.state.position_distrution_png}
                          />
                        </Card.Body>
                        <Card style={{ marginLeft: "2%" }}>
                          <Card.Body>
                            <Card.Title>
                              This is top-100 players distribution classified by
                              position
                            </Card.Title>
                            <img
                              className="img-format"
                              src={this.state.new_player_distribution_png}
                            />
                          </Card.Body>
                          <Card style={{ marginLeft: "2%" }}>
                            <Card.Body>
                              <Card.Title>
                                New Player was marked by "+" and other top-100
                                players were marked by "o".
                              </Card.Title>
                              <Card.Text>
                                From this result, we can see that Joe Harris's
                                performance is the closest approximation to out
                                new_players under the same position. different
                                positions were marked by different colors which
                                showed by legend.
                              </Card.Text>
                              <img
                                className="img-format_version2"
                                src={this.state.result}
                              />
                            </Card.Body>
                          </Card>
                        </Card>
                      </Card>
                    </Card>
                  </Card>
                </Card>
              </Card>
            </Card>
          </Card>
        </Card.Body>
      </Card>
    );
  }
}

export default NewPlayerPage;
